# Generated by Django 5.0.1 on 2024-03-24 21:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cpf', models.CharField(max_length=100)),
                ('Nome', models.CharField(max_length=100)),
                ('Crm', models.CharField(max_length=100)),
                ('Rg', models.CharField(max_length=100)),
                ('ReconhecimentoFacial', models.ImageField(upload_to='ReconhecimentoFacial')),
                ('TipoUsuario', models.CharField(max_length=20)),
                ('login', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='UserLogin', to=settings.AUTH_USER_MODEL, verbose_name='UserLogin')),
            ],
            options={
                'db_table': 'UserProfile',
            },
        ),
    ]
