# Generated by Django 5.0.1 on 2024-04-08 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='ReconhecimentoFacial',
            field=models.ImageField(blank=True, null=True, upload_to='ReconhecimentoFacial'),
        ),
    ]
