# Generated by Django 5.0.1 on 2024-04-08 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medicamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nome', models.CharField(max_length=100)),
                ('RFID', models.CharField(max_length=100)),
                ('Quantidade', models.IntegerField()),
                ('Porta', models.IntegerField()),
                ('DataCriacao', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'Medicamento',
            },
        ),
    ]
